name: Build and Test
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  api_test:
    name: API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.3

      - name: Lint Go Code
        run: staticcheck ./...

      - name: Install Dependencies
        run: go version

      - name: Run Unit Tests
        run: go test -v -coverprofile=coverage.txt -covermode=atomic --race ./...

  api_build:
    name: API Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: go version

      - name: Build
        run: go build ./cmd/...

  web_test:
    name: Web Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json

      - name: Install Dependencies
        working-directory: ./web
        run: npm install

      - name: Lint React Code
        working-directory: ./web
        run: npm run lint

      - name: Run React Tests
        working-directory: ./web
        run: npm run test

  web_build:
    name: Web Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json

      - name: Install Dependencies
        working-directory: ./web
        run: npm install

      - name: Build React Bundle
        working-directory: ./web
        run: npm run build
