name: Deploy to Cloud Run
on:
  push:
    tags:
      - 'v*'

jobs:
  api_deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    env:
      SENTRY_DSN: ${{ secrets.WHISPER_API_SENTRY_DSN }}
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/whisper-api

    steps:
      - name: Login to Google
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Version Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get Git Revision
        run: echo "GIT_REVISION=$(git rev-parse --shorte HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build \
            -f containers/api/Dockerfile \
            --build-arg GIT_REVISION=$GIT_REVISION \
            --build-arg SENTRY_DSN=$SENTRY_DSN \
            -t $IMAGE_NAME:$RELEASE_VERSION .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME:$RELEASE_VERSION

      - name: Deploy Docker Image
        run: |
          gcloud run deploy whisper-api \
            --image $IMAGE_NAME:$RELEASE_VERSION \
            --region us-east1 --platform managed \
            --cpu 1 --memory 512Mi --port 8318 \
            --max-instances 16 --concurrency 48 \
            --allow-unauthenticated

  web_deploy:
    name: Deploy Web UI
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/whisper-ui
      SENTRY_DSN: ${{ secrets.WHISPER_WEB_SENTRY_DSN }}
    steps:
      - name: Login to Google
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Version Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get Git Revision
        run: echo "GIT_REVISION=$(git rev-parse --shorte HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build \
            -f containers/web/Dockerfile \
            --build-arg REACT_APP_API_BASE_URL=https://api.whisper.rotational.dev/v1 \
            --build-arg REACT_APP_UI_BASE_URL=https://whisper.rotational.dev \
            --build-arg REACT_APP_GIT_REVISION=$GIT_REVISION \
            --build-arg REACT_APP_SENTRY_DSN=$SENTRY_DSN \
            --build-arg REACT_APP_RELEASE_VERSION=$RELEASE_VERSION \
            --build-arg NODE_ENV=production \
            -t $IMAGE_NAME:$RELEASE_VERSION .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME:$RELEASE_VERSION

      - name: Deploy Docker Image
        run: |
          gcloud run deploy whisper-ui \
            --image $IMAGE_NAME:$RELEASE_VERSION \
            --region us-east1 --platform managed \
            --cpu 1 --memory 512Mi \
            --max-instances 16 --concurrency 48 \
            --allow-unauthenticated
